main: edu.unca.atjones.Backpacks.Backpacks
name: Backpacks
version: 0.1
author: Pseudothrax
description: More Carrying space with backpacks
commands:
  bkpcreate:
    description: Create backpacks
    usage: /<command> <backpack> <size> [player]
  bkpgrant:
    description: Grant rewards to users
    usage: /<command> <player> <num>|1
  bkphelp:
    description: View usage tips
    usage: /<command>
  bkplist:
    description: View a list of backpacks
    usage: /<command> [player]
  bkpopen:
    description: Open backpacks
    usage: /<command> <backpack> [player]
  bkpremove:
    description: Remove backpacks
    usage: /<command> <backpack> [player]
  bkprename:
    description: Rename backpacks
    usage: /<command> <old> <new> [player]
  bkproute:
    description: Route items into backpacks
    usage: /<command> <item> <backpack> [player]
  bkproutes:
    description: View all defined routes
    usage: /<command> [player]
  bkpupgrade:
    description: Upgrade a backpack
    usage: /<command> <backpack> [player]
  bkprewards:
    description: View available reward count
    usage: /<command> [player]
    
permissions:
  backpacks.*:
    description: gives all basic backpack commands
    default: true
    children:
      backpacks.autoreward: true
      backpacks.create: true
      backpacks.help: true
      backpacks.list: true
      backpacks.open: true
      backpacks.rename: true
      backpacks.route: true
      backpacks.routes: true
      backpacks.upgrade: true
      backpacks.rewards: true
    
  backpacks.autoreward:
    description: allows players to collect rewards by breaking blocks
    default: true
  backpacks.create:
    description: allows players to create backpacks
    default: true
  backpacks.help:
    description: allows access to the backpacks help
    default: true
  backpacks.list:
    description: allows players to view a list of backpacks
    default: true
  backpacks.open:
    description: allows players to open backpacks
    default: true
  backpacks.rename:
    description: allows players to rename backpacks
    default: true
  backpacks.route:
    description: allows players to route items 
    default: true
  backpacks.routes:
    description: allows players to view a list of routes
    default: true
  backpacks.upgrade:
    description: allows players to upgrade backpacks
    default: true
  backpacks.rewards:
    description: allows players to view their available rewards
    default: true
    
  backpacks.admin.*:
    description: gives all admin backpack commands
    default: op
    children:
      backpacks.admin.create: true
      backpacks.admin.grant: true
      backpacks.admin.list: true
      backpacks.admin.open: true
      backpacks.admin.rename: true
      backpacks.admin.remove: true
      backpacks.admin.route: true
      backpacks.admin.routes: true
      backpacks.admin.upgrade: true
      backpacks.admin.rewards: true
    
  backpacks.admin.create:
    description: allows admins to create backpacks for anyone
    default: op
  backpacks.admin.grant:
    description: allows admins to reward players
    default: op
  backpacks.admin.list:
    description: allows admins to view a list of anyone's backpacks
    default: op
  backpacks.admin.open:
    description: allows admins to open anyone's backpack
    default: op
  backpacks.admin.rename:
    description: allows admins to view a list of anyone's backpacks
    default: op
  backpacks.admin.remove:
    description: allows admins to destroy anyone's backpacks
    default: op
  backpacks.admin.route:
    description: allows admins to route anyone's items
    default: op
  backpacks.admin.routes:
    description: allows admins to view a list of anyone's routes
    default: op
  backpacks.admin.upgrade:
    description: allows admins to upgrade anyone's backpack
    default: op
  backpacks.admin.rewards:
    description: allows admins to view anyone's available rewards
    default: op